DEFINE_INSN(addi)
DEFINE_INSN(lw)
DEFINE_INSN(ld)
DEFINE_INSN(sw)
DEFINE_INSN(sd)
DEFINE_INSN(jal)
DEFINE_INSN(bne)
DEFINE_INSN(add)
DEFINE_INSN(addiw)
DEFINE_INSN(lui)

DEFINE_INSN(sub)
DEFINE_INSN(sll)
DEFINE_INSN(slt)
DEFINE_INSN(sltu)
DEFINE_INSN(xor)
DEFINE_INSN(srl)
DEFINE_INSN(sra)
DEFINE_INSN(or)

DEFINE_INSN(and)
DEFINE_INSN(slli)
DEFINE_INSN(slti)
DEFINE_INSN(sltiu)
DEFINE_INSN(xori)
DEFINE_INSN(srli)
DEFINE_INSN(srai)
DEFINE_INSN(ori)
DEFINE_INSN(andi)

DEFINE_INSN(beq)

DEFINE_INSN(blt)
DEFINE_INSN(bge)
DEFINE_INSN(bltu)
DEFINE_INSN(bgeu)

DEFINE_INSN(lb)
DEFINE_INSN(lh)
DEFINE_INSN(lbu)
DEFINE_INSN(lhu)
DEFINE_INSN(lwu)


DEFINE_INSN(sb)
DEFINE_INSN(sh)


DEFINE_INSN(jalr)
DEFINE_INSN(auipc)


DEFINE_INSN(addw)
DEFINE_INSN(subw)
DEFINE_INSN(sllw)
DEFINE_INSN(srlw)
DEFINE_INSN(sraw)


DEFINE_INSN(slliw)
DEFINE_INSN(srliw)
DEFINE_INSN(sraiw)

DEFINE_INSN(mul)
DEFINE_INSN(mulw)
DEFINE_INSN(mulh)
DEFINE_INSN(mulhu)
DEFINE_INSN(mulhsu)

DEFINE_INSN(div)
DEFINE_INSN(divu)
DEFINE_INSN(divw)
DEFINE_INSN(divuw)
DEFINE_INSN(rem)
DEFINE_INSN(remu)
DEFINE_INSN(remw)
DEFINE_INSN(remuw)

DEFINE_INSN(scall)

// DEFINE_INSN(csrrw)
// DEFINE_INSN(csrrc)
// DEFINE_INSN(csrrs)

DEFINE_INSN(fence)

DEFINE_INSN(fld)
DEFINE_INSN(flw)
DEFINE_INSN(fsd)
DEFINE_INSN(fsw)

DEFINE_INSN(fmv_s_x)

DEFINE_INSN(fmul_d)
DEFINE_INSN(fdiv_d)
DEFINE_INSN(fmul_s)
DEFINE_INSN(fdiv_s)

DEFINE_INSN(fadd_d)
DEFINE_INSN(fsub_d)
DEFINE_INSN(fadd_s)
DEFINE_INSN(fsub_s)

DEFINE_INSN(fmv_x_d)
DEFINE_INSN(fmv_d_x)

DEFINE_INSN(fcvt_l_d)

DEFINE_INSN(fcvt_s_l)
DEFINE_INSN(fcvt_s_w)
DEFINE_INSN(fcvt_s_d)
DEFINE_INSN(fcvt_d_s)
DEFINE_INSN(fcvt_d_w)
DEFINE_INSN(fcvt_d_l)
DEFINE_INSN(fcvt_w_d)
DEFINE_INSN(fcvt_wu_d)


DEFINE_INSN(fsgnj_d)
DEFINE_INSN(feq_d)
DEFINE_INSN(fle_d)
DEFINE_INSN(flt_d)
DEFINE_INSN(fmadd_d)


// DEFINE_INSN(sret)